version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 012345678910.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=860061945305.dkr.ecr.ap-south-1.amazonaws.com/komala-pension-management-portal
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd process-pension
      - docker build -t process-pension .
      - docker tag process-pension 860061945305.dkr.ecr.ap-south-1.amazonaws.com/komala-pension-management-portal:process-pension
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 860061945305.dkr.ecr.ap-south-1.amazonaws.com/komala-pension-management-portal:process-pension
      - echo Writing image definitions file...
      - printf '[{"name":"process-pension","imageUri":"%s"}]' 860061945305.dkr.ecr.ap-south-1.amazonaws.com/komala-pension-management-portal:process-pension > imagedefinitions.json
artifacts:
    files: process-pension/imagedefinitions.json