version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/pensioner-auth-task-def:1"
        LoadBalancerInfo:
          ContainerName: "pensioner-auth-container"
          ContainerPort: "8080"
        PlatformVersion: "LATEST"