version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=860061945305.dkr.ecr.ap-south-1.amazonaws.com/komala-pension-management-portal
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd pmp
      - docker build -t pmp-server .
      - docker tag pmp-server 860061945305.dkr.ecr.ap-south-1.amazonaws.com/komala-pension-management-portal:pmp
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 860061945305.dkr.ecr.ap-south-1.amazonaws.com/komala-pension-management-portal:pmp
      - echo Writing image definitions file...
      - printf '[{"name":"pmp-server","imageUri":"%s"}]' 860061945305.dkr.ecr.ap-south-1.amazonaws.com/komala-pension-management-portal:pmp > imagedefinitions.json
artifacts:
    files: pmp/imagedefinitions.json